import type { Lang } from "./translations";

const ui = {
  es: {
    toast: {
      prefix: "Alguien en",
      suffix: "acaba de valorar su propiedad",
    },
    pdf: {
      title:     "Informe de Valoración",
      subtitle:  "Informe profesional · Gemini 2.5 Flash",
      details:   "Detalles de la propiedad",
      estimated: "Valor de mercado estimado",
      suggested: "Precio sugerido",
      range:     "Rango de precios",
      min:       "Mínimo",
      max:       "Máximo",
      analysis:  "Análisis completo · Gemini IA",
      footer:    "Generado por CalculaTuCasa.com",
      filename:  "informe-valoracion",
      btn:       "Descargar Informe PDF",
    },
    map: { loading: "Cargando mapa..." },
  },
  ca: {
    toast: {
      prefix: "Algú a",
      suffix: "acaba de valorar el seu habitatge",
    },
    pdf: {
      title:     "Informe de Valoració",
      subtitle:  "Informe professional · Gemini 2.5 Flash",
      details:   "Detalls de la propietat",
      estimated: "Valor de mercat estimat",
      suggested: "Preu suggerit",
      range:     "Rang de preus",
      min:       "Mínim",
      max:       "Màxim",
      analysis:  "Anàlisi completa · Gemini IA",
      footer:    "Generat per CalculaTuCasa.com",
      filename:  "informe-valoracio",
      btn:       "Descarregar Informe PDF",
    },
    map: { loading: "Carregant mapa..." },
  },
  en: {
    toast: {
      prefix: "Someone in",
      suffix: "just valued their home",
    },
    pdf: {
      title:     "Valuation Report",
      subtitle:  "Professional Report · Gemini 2.5 Flash",
      details:   "Property details",
      estimated: "Estimated market value",
      suggested: "Suggested price",
      range:     "Price range",
      min:       "Minimum",
      max:       "Maximum",
      analysis:  "Full analysis · Gemini AI",
      footer:    "Generated by CalculaTuCasa.com",
      filename:  "valuation-report",
      btn:       "Download PDF Report",
    },
    map: { loading: "Loading map..." },
  },
} as const;

export function U(lang: Lang) { return ui[lang]; }
