import type { Lang } from "./translations";

const ui = {
  es: {
    toast: {
      prefix: "Alguien en",
      suffix: "acaba de valorar su propiedad",
      phrases: [
        (name: string, loc: string, price: string) => `${name} de ${loc} acaba de descubrir que su piso vale ~${price}`,
        (name: string, loc: string, price: string) => `${name} de ${loc} acaba de valorar su vivienda: ~${price}`,
        (name: string, loc: string, price: string) => `${name} de ${loc} conoce ya el valor de su casa: ~${price}`,
      ] as const,
    },
    pdf: {
      // ── existentes ──────────────────────────────────────────────────────────
      title:        "Informe de Valoración",
      subtitle:     "Informe profesional · Gemini 2.5 Flash",
      details:      "Detalles de la propiedad",
      estimated:    "Valor de mercado estimado",
      suggested:    "Precio sugerido",
      range:        "Rango de precios",
      min:          "Mínimo",
      max:          "Máximo",
      analysis:     "Análisis completo · Gemini IA",
      energyImpact: "Impacto Energético",
      footer:       "Generado por CalculaTuCasa.com",
      filename:     "informe-valoracion",
      btn:          "Descargar Informe PDF",
      // ── portada ─────────────────────────────────────────────────────────────
      portada_titulo:       "INFORME DE VALORACION INMOBILIARIA",
      portada_exclusivo:    "Preparado exclusivamente para",
      portada_confidencial: "Este informe es confidencial y ha sido generado exclusivamente para el destinatario indicado.",
      portada_metodologia:  ["Datos reales del mercado", "IA Gemini 2.5 Flash", "+2.400 valoraciones"],
      // ── página 2 ────────────────────────────────────────────────────────────
      pag2_titulo:      "Analisis de Mercado",
      pag2_comparables: "Comparables de Mercado",
      pag2_precio_m2:   "Precio EUR/m2 comparativo",
      pag2_tendencia:   "Tendencia de mercado 12 meses",
      // ── página 3 ────────────────────────────────────────────────────────────
      pag3_titulo:       "Tu Barrio en Detalle",
      pag3_puntuacion:   "Puntuacion de servicios",
      pag3_tipo_barrio:  "Tipo de barrio",
      pag3_ventajas:     "Ventajas de la ubicacion",
      // ── página 4 ────────────────────────────────────────────────────────────
      pag4_titulo:            "Perspectiva Financiera",
      pag4_alquiler:          "Precio de alquiler estimado",
      pag4_rentabilidad:      "Rentabilidad bruta",
      pag4_tiempo_venta:      "Tiempo estimado de venta",
      pag4_escenarios:        "Escenarios de inversion",
      pag4_costes_comprador:  "Costes estimados para el comprador",
      pag4_costes_vendedor:   "Costes estimados para el vendedor",
      pag4_hipoteca:          "Estimacion de hipoteca",
      pag4_ibi:               "IBI estimado anual",
      pag4_siguientes:        "Siguientes pasos",
      pag4_recomendacion:     "Recomendacion del tasador IA",
      // ── métricas ────────────────────────────────────────────────────────────
      score_inversion:    "Score de Inversion",
      posicion_mercado:   "Posicion en el mercado local",
      puntos_fuertes:     "Puntos Fuertes",
      puntos_mejorar:     "Puntos a Mejorar",
      // ── categorías entorno ──────────────────────────────────────────────────
      cat_colegios:      "Colegios",
      cat_supermercados: "Supermercados",
      cat_farmacias:     "Farmacias",
      cat_transporte:    "Transporte",
      cat_parques:       "Parques",
      cat_restaurantes:  "Restaurantes",
      cat_gasolineras:   "Gasolineras",
      cat_salud:         "Centros de salud",
    },
    map: { loading: "Cargando mapa..." },
  },
  ca: {
    toast: {
      prefix: "Algu a",
      suffix: "acaba de valorar el seu habitatge",
      phrases: [
        (name: string, loc: string, price: string) => `${name} de ${loc} acaba de descobrir que el seu pis val ~${price}`,
        (name: string, loc: string, price: string) => `${name} de ${loc} acaba de valorar el seu habitatge: ~${price}`,
        (name: string, loc: string, price: string) => `${name} de ${loc} ja coneix el valor de casa seva: ~${price}`,
      ] as const,
    },
    pdf: {
      // ── existents ───────────────────────────────────────────────────────────
      title:        "Informe de Valoracio",
      subtitle:     "Informe professional · Gemini 2.5 Flash",
      details:      "Detalls de la propietat",
      estimated:    "Valor de mercat estimat",
      suggested:    "Preu suggerit",
      range:        "Rang de preus",
      min:          "Minim",
      max:          "Maxim",
      analysis:     "Analisi completa · Gemini IA",
      energyImpact: "Impacte Energetic",
      footer:       "Generat per CalculaTuCasa.com",
      filename:     "informe-valoracio",
      btn:          "Descarregar Informe PDF",
      // ── portada ─────────────────────────────────────────────────────────────
      portada_titulo:       "INFORME DE VALORACIO IMMOBILIARIA",
      portada_exclusivo:    "Preparat exclusivament per a",
      portada_confidencial: "Aquest informe es confidencial i ha estat generat exclusivament per al destinatari indicat.",
      portada_metodologia:  ["Dades reals del mercat", "IA Gemini 2.5 Flash", "+2.400 valoracions"],
      // ── pagina 2 ────────────────────────────────────────────────────────────
      pag2_titulo:      "Analisi de Mercat",
      pag2_comparables: "Comparables de Mercat",
      pag2_precio_m2:   "Preu EUR/m2 comparatiu",
      pag2_tendencia:   "Tendencia de mercat 12 mesos",
      // ── pagina 3 ────────────────────────────────────────────────────────────
      pag3_titulo:       "El Teu Barri en Detall",
      pag3_puntuacion:   "Puntuacio de serveis",
      pag3_tipo_barrio:  "Tipus de barri",
      pag3_ventajas:     "Avantatges de la ubicacio",
      // ── pagina 4 ────────────────────────────────────────────────────────────
      pag4_titulo:            "Perspectiva Financera",
      pag4_alquiler:          "Preu de lloguer estimat",
      pag4_rentabilidad:      "Rendibilitat bruta",
      pag4_tiempo_venta:      "Temps estimat de venda",
      pag4_escenarios:        "Escenaris d'inversio",
      pag4_costes_comprador:  "Costos estimats per al comprador",
      pag4_costes_vendedor:   "Costos estimats per al venedor",
      pag4_hipoteca:          "Estimacio d'hipoteca",
      pag4_ibi:               "IBI estimat anual",
      pag4_siguientes:        "Seguents passos",
      pag4_recomendacion:     "Recomanacio del taxador IA",
      // ── metriques ───────────────────────────────────────────────────────────
      score_inversion:    "Score d'Inversio",
      posicion_mercado:   "Posicio en el mercat local",
      puntos_fuertes:     "Punts Forts",
      puntos_mejorar:     "Punts a Millorar",
      // ── categories entorn ───────────────────────────────────────────────────
      cat_colegios:      "Col·legis",
      cat_supermercados: "Supermercats",
      cat_farmacias:     "Farmacies",
      cat_transporte:    "Transport",
      cat_parques:       "Parcs",
      cat_restaurantes:  "Restaurants",
      cat_gasolineras:   "Gasolineres",
      cat_salud:         "Centres de salut",
    },
    map: { loading: "Carregant mapa..." },
  },
  en: {
    toast: {
      prefix: "Someone in",
      suffix: "just valued their home",
      phrases: [
        (name: string, loc: string, price: string) => `${name} from ${loc} just discovered their apartment is worth ~${price}`,
        (name: string, loc: string, price: string) => `${name} from ${loc} just valued their home: ~${price}`,
        (name: string, loc: string, price: string) => `${name} from ${loc} now knows their home's value: ~${price}`,
      ] as const,
    },
    pdf: {
      // ── existing ────────────────────────────────────────────────────────────
      title:        "Valuation Report",
      subtitle:     "Professional Report · Gemini 2.5 Flash",
      details:      "Property details",
      estimated:    "Estimated market value",
      suggested:    "Suggested price",
      range:        "Price range",
      min:          "Minimum",
      max:          "Maximum",
      analysis:     "Full analysis · Gemini AI",
      energyImpact: "Energy Impact",
      footer:       "Generated by CalculaTuCasa.com",
      filename:     "valuation-report",
      btn:          "Download PDF Report",
      // ── cover ───────────────────────────────────────────────────────────────
      portada_titulo:       "REAL ESTATE VALUATION REPORT",
      portada_exclusivo:    "Prepared exclusively for",
      portada_confidencial: "This report is confidential and has been generated exclusively for the indicated recipient.",
      portada_metodologia:  ["Real market data", "Gemini 2.5 Flash AI", "+2,400 valuations"],
      // ── page 2 ──────────────────────────────────────────────────────────────
      pag2_titulo:      "Market Analysis",
      pag2_comparables: "Market Comparables",
      pag2_precio_m2:   "Comparative price EUR/sqm",
      pag2_tendencia:   "12-month market trend",
      // ── page 3 ──────────────────────────────────────────────────────────────
      pag3_titulo:       "Your Neighbourhood in Detail",
      pag3_puntuacion:   "Services score",
      pag3_tipo_barrio:  "Neighbourhood type",
      pag3_ventajas:     "Location advantages",
      // ── page 4 ──────────────────────────────────────────────────────────────
      pag4_titulo:            "Financial Perspective",
      pag4_alquiler:          "Estimated rental price",
      pag4_rentabilidad:      "Gross yield",
      pag4_tiempo_venta:      "Estimated time to sell",
      pag4_escenarios:        "Investment scenarios",
      pag4_costes_comprador:  "Estimated buyer costs",
      pag4_costes_vendedor:   "Estimated seller costs",
      pag4_hipoteca:          "Mortgage estimate",
      pag4_ibi:               "Estimated annual property tax",
      pag4_siguientes:        "Next steps",
      pag4_recomendacion:     "AI appraiser recommendation",
      // ── metrics ─────────────────────────────────────────────────────────────
      score_inversion:    "Investment Score",
      posicion_mercado:   "Position in local market",
      puntos_fuertes:     "Strengths",
      puntos_mejorar:     "Areas to Improve",
      // ── environment categories ───────────────────────────────────────────────
      cat_colegios:      "Schools",
      cat_supermercados: "Supermarkets",
      cat_farmacias:     "Pharmacies",
      cat_transporte:    "Transport",
      cat_parques:       "Parks",
      cat_restaurantes:  "Restaurants",
      cat_gasolineras:   "Petrol stations",
      cat_salud:         "Health centres",
    },
    map: { loading: "Loading map..." },
  },
} as const;

export function U(lang: Lang) { return ui[lang]; }
export type UiStrings = ReturnType<typeof U>;
